// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardController from "./dashboard_controller"

// this is where the `data-controller` value comes from, i.e. 'dashboard'
application.register("dashboard", DashboardController)
