##### EXAMPLE:
# Style/Encoding:
#  Enabled: false
#
#Layout/LineLength:
#  Max: 99
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Style/BlockComments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

Metrics/BlockLength:
  Max: 200

Metrics/MethodLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Style/Lambda:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/MultipleExpectations:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
