require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  NewCops: enable

### STYLE ###
Style/BlockComments:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false

### LAYOUT ###
Layout/HashAlignment:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false

### RAILS ###
Rails/I18nLocaleTexts:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false

### METRICS ###
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 200
Metrics/MethodLength:
  Enabled: false

### RSPEC ###
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

### FACTORYBOT ###
FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

### NAMING CONVENTIONS ###
Naming/MemoizedInstanceVariableName:
  Enabled: false
