name: RuboCop

on: [pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    
    - run: echo $PATH | tr ':' '\n'
    - run: bundle info rubocop
    - run: gem which rubocop
    - name: Lint Ruby files
      run: rubocop --parallel